// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zCertification = z.object({
    name: z.optional(z.string()),
    issuer: z.optional(z.string()),
    date: z.optional(z.iso.date())
});

export const zEducation = z.object({
    school: z.optional(z.string()),
    degree: z.optional(z.string()),
    fieldOfStudy: z.optional(z.string()),
    startDate: z.optional(z.iso.date()),
    endDate: z.optional(z.iso.date())
});

export const zSummary = z.object({
    text: z.optional(z.string()),
    technologies: z.optional(z.array(z.string()))
});

export const zExperience = z.object({
    position: z.optional(z.string()),
    company: z.optional(z.string()),
    url: z.optional(z.string()),
    location: z.optional(z.string()),
    startDate: z.optional(z.iso.date()),
    endDate: z.optional(z.iso.date()),
    summaries: z.optional(z.array(zSummary))
});

export const zPersonalInfo = z.object({
    firstName: z.string(),
    lastName: z.string(),
    email: z.optional(z.string()),
    phone: z.optional(z.string()),
    role: z.optional(z.string()),
    summary: z.optional(z.string()),
    linkedIn: z.optional(z.string()),
    github: z.optional(z.string()),
    website: z.optional(z.string()),
    other: z.optional(z.string())
});

export const zLanguage = z.object({
    language: z.optional(z.string()),
    level: z.optional(z.enum([
        'A1',
        'A2',
        'B1',
        'B2',
        'C1',
        'C2'
    ]))
});

export const zProject = z.object({
    name: z.optional(z.string()),
    url: z.optional(z.string()),
    summaries: z.optional(z.array(zSummary))
});

export const zUserCv = z.object({
    personalInfo: zPersonalInfo,
    skills: z.optional(z.array(z.string())),
    experience: z.optional(z.array(zExperience)),
    education: z.optional(z.array(zEducation)),
    languages: z.optional(z.array(zLanguage)),
    certifications: z.optional(z.array(zCertification)),
    projects: z.optional(z.array(zProject))
});

export const zGeneratePdfRequest = z.object({
    userCV: zUserCv,
    template: z.string(),
    language: z.enum([
        'EN',
        'PL'
    ])
});

export const zErrorResponse = z.object({
    timestamp: z.optional(z.iso.datetime()),
    status: z.optional(z.int()),
    error: z.optional(z.string()),
    message: z.optional(z.string()),
    details: z.optional(z.array(z.string()))
});

export const zSkillItem = z.object({
    name: z.optional(z.string()),
    score: z.optional(z.number())
});

export const zSkillResult = z.object({
    hardSkills: z.optional(z.array(zSkillItem)),
    softSkills: z.optional(z.array(zSkillItem)),
    tools: z.optional(z.array(zSkillItem))
});

export const zPrepareCvRequest = z.object({
    userCV: zUserCv,
    skillResult: zSkillResult
});

export const zJobOffer = z.object({
    url: z.optional(z.string()),
    company: z.optional(z.string()),
    title: z.optional(z.string()),
    description: z.optional(z.string()),
    technologies: z.optional(z.array(z.string())),
    requirements: z.optional(z.array(z.string())),
    responsibilities: z.optional(z.array(z.string()))
});

export const zGeneratePdfData = z.object({
    body: zGeneratePdfRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPrepareCvData = z.object({
    body: zPrepareCvRequest,
    path: z.optional(z.never()),
    query: z.optional(z.object({
        topN: z.optional(z.unknown())
    }))
});

/**
 * CV successfully prepared
 */
export const zPrepareCvResponse = zUserCv;

export const zScrapeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        url: z.unknown()
    })
});

/**
 * Job offer successfully scraped
 */
export const zScrapeResponse = zJobOffer;
